FROM ubuntu:xenial

RUN apt-get update && apt-get install -y wget
RUN wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/containerd/containerd-1.4.1/containerd-1.4.1.linux-ppc64le.tar.gz
RUN tar xvf containerd-1.4.1.linux-ppc64le.tar.gz
